import { config, dom, library } from "@fortawesome/fontawesome-svg-core";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import {
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faCircleExclamation,
    faDeleteLeft,
    faEraser,
    faGlobe,
    faMusic,
    faPause,
    faPlay,
    faRankingStar,
    faRepeat,
    faRotateLeft,
    faRotateRight,
    faSearch,
    faThumbsUp,
    faTriangleExclamation,
    faVolumeHigh,
    faVolumeLow,
    faVolumeXmark,
    faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
    faClock as farClock,
    faEye as farEye,
    faThumbsUp as farThumbsUp,
} from "@fortawesome/free-regular-svg-icons";

config.autoReplaceSvg = false;

// @ts-ignore
library.add(
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faCircleExclamation,
    faGithub,
    faGlobe,
    faPause,
    faPlay,
    faRankingStar,
    farClock,
    farEye,
    farThumbsUp,
    faThumbsUp,
    faTriangleExclamation,
    faXmark,
    faVolumeXmark,
    faVolumeLow,
    faVolumeHigh,
    faRepeat,
    faMusic,
    faSearch,
    faRotateRight,
    faRotateLeft,
    faEraser,
    faDeleteLeft,
);
dom.watch();
